services:
  - type: web
    name: discord-otp-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:5000 bot:app
    autoDeploy: true
